milestone:
  - verify_consumer:
      semanticLock:
        pending: startcheck
        approval: checked
        rejected: failed
  - create_ticket:
      semanticLock:
        pending: startcheck
        approval: checked
        rejected: failed
  - verify_card:
      semanticLock:
        pending: startcheck
        approval: checked
        rejected: failed
  - confirm_ticket:
      semanticLock:
        pending: start
        approval: confirm
  - confirm_order:
      semanticLock:
        pending: start
        approval: confirm
